# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/sony/loire-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter suzu kugo,$(TARGET_DEVICE)),)

endif
